services:
  app:
    build: .
    container_name: rustymcpriceface
    restart: unless-stopped
    volumes:
      - ./shared:/app/shared
    environment:
      - RUST_LOG=info,rustymcpriceface=info,discord_bot=info
      - UPDATE_INTERVAL_SECONDS=${UPDATE_INTERVAL_SECONDS:-12}
      - CLEANUP_INTERVAL_HOURS=${CLEANUP_INTERVAL_HOURS:-24}
      - CRYPTO_FEEDS=${CRYPTO_FEEDS:-BTC:0xe62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43,ETH:0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace,SOL:0xef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d,DXY:yahoo_finance}
      
      # Bot Tokens
      - DISCORD_TOKEN_BTC=${DISCORD_TOKEN_BTC}
      - DISCORD_TOKEN_ETH=${DISCORD_TOKEN_ETH}
      - DISCORD_TOKEN_SOL=${DISCORD_TOKEN_SOL}
      - DISCORD_TOKEN_DOGE=${DISCORD_TOKEN_DOGE}
      - DISCORD_TOKEN_AVAX=${DISCORD_TOKEN_AVAX}
      - DISCORD_TOKEN_BNB=${DISCORD_TOKEN_BNB}
      - DISCORD_TOKEN_SUI=${DISCORD_TOKEN_SUI}
      - DISCORD_TOKEN_SEI=${DISCORD_TOKEN_SEI}
      - DISCORD_TOKEN_JLP=${DISCORD_TOKEN_JLP}
      - DISCORD_TOKEN_PUMP=${DISCORD_TOKEN_PUMP}
      - DISCORD_TOKEN_XPL=${DISCORD_TOKEN_XPL}
      - DISCORD_TOKEN_MSTR=${DISCORD_TOKEN_MSTR}
      - DISCORD_TOKEN_OIL=${DISCORD_TOKEN_OIL}
      - DISCORD_TOKEN_VOO=${DISCORD_TOKEN_VOO}
      - DISCORD_TOKEN_DXY=${DISCORD_TOKEN_DXY}
      - DISCORD_TOKEN_HOOD=${DISCORD_TOKEN_HOOD}
      - DISCORD_TOKEN_SBET=${DISCORD_TOKEN_SBET}
      - DISCORD_TOKEN_GOLD=${DISCORD_TOKEN_GOLD}
      - DISCORD_TOKEN_SILVER=${DISCORD_TOKEN_SILVER}
      - DISCORD_TOKEN_FARTCOIN=${DISCORD_TOKEN_FARTCOIN}
      - DISCORD_TOKEN_2Z=${DISCORD_TOKEN_2Z}
      - DISCORD_TOKEN_ASTER=${DISCORD_TOKEN_ASTER}
      - DISCORD_TOKEN_EURO=${DISCORD_TOKEN_EURO}
      - DISCORD_TOKEN_SHANGHAISILVER=${DISCORD_TOKEN_SHANGHAISILVER}
      - DISCORD_TOKEN_SHANGHAI=${DISCORD_TOKEN_SHANGHAI}


    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
