[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[build]
# Enable link-time optimization for smaller binaries
rustflags = ["-C", "link-arg=-s"]

[profile.release]
# Optimize for size and performance
opt-level = "z"          # Optimize for size
lto = true              # Link-time optimization
codegen-units = 1       # Better optimization
panic = "abort"         # Smaller binaries
strip = true           # Remove debug symbols